apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hj033vb4e-python 
  janus-idp.io/tekton: hj033vb4e-python
  backstage.io/kubernetes-id: hj033vb4e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hj033vb4e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml